python3 src/train_t5.py --data data/citations/t5_citations_json.pickle --epochs 5 --batch_size 1 --base_model t5 --save models/t5/association_json --wandb true --wandb_name association_json --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_newline.pickle --epochs 5 --batch_size 1 --base_model t5 --save models/t5/association_newline --wandb true --wandb_name association_newline --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_original.pickle --epochs 5 --batch_size 1 --base_model t5 --save models/t5/association_original --wandb true --wandb_name association_original --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_json.pickle --epochs 10 --batch_size 1 --base_model t5 --save models/t5/association_json_10 --wandb true --wandb_name association_json_10 --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_newline.pickle --epochs 10 --batch_size 1 --base_model t5 --save models/t5/association_newline_10 --wandb true --wandb_name association_newline_10 --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_original.pickle --epochs 10 --batch_size 1 --base_model t5 --save models/t5/association_original_10 --wandb true --wandb_name association_original_10 --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_json.pickle --epochs 25 --batch_size 1 --base_model t5 --save models/t5/association_json_25 --wandb true --wandb_name association_json_25 --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_newline.pickle --epochs 25 --batch_size 1 --base_model t5 --save models/t5/association_newline_25 --wandb true --wandb_name association_newline_25 --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_original.pickle --epochs 25 --batch_size 1 --base_model t5 --save models/t5/association_original_25 --wandb true --wandb_name association_original_25 --mode association --errors false
python3 src/train_t5.py --data data/citations/t5_citations_json.pickle --epochs 5 --batch_size 1 --base_model t5 --save models/t5/constrained_association_json --wandb true --wandb_name constrained_association_json --mode association --errors false --extra_delim "{ } , },"
python3 src/train_t5.py --data data/citations/t5_citations_newline.pickle --epochs 5 --batch_size 1 --base_model t5 --save models/t5/constrained_association_newline --wandb true --wandb_name constrained_association_newline --mode association --errors false --extra_delim "{ } <"
python3 src/train_t5.py --data data/citations/t5_citations_original.pickle --epochs 5 --batch_size 1 --base_model t5 --save models/t5/constrained_association_original --wandb true --wandb_name constrained_association_original --mode association --errors false --extra_delim "< > / </"
